
---
title: "`OMERarr`"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
package: "`r BiocStyle::pkg_ver('OMERarr')`"
author: 
  - name: Artur Manukyan
output:
  BiocStyle::html_document
vignette: |
  %\VignetteIndexEntry{OMERarr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r load-libs}n

# library(OMERarr)
library(Rarr)
library(EBImage)
```

# Introduction

# Installation

You can install `r Biocpkg("ImageArray")` from Bioconductor with:

```{r install-BiocManager, eval = FALSE}
library(Rarr)
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}
BiocManager::install("OMERarr")
```

# Usage

```{r read_temp, eval = FALSE}
chick <- "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0073A/9798462.zarr"
# chich_array <- read_zarr_array(zarr_array_path = file.path(chick, "3"))
chich_meta <- read_zarr_attributes(zarr_path = chick, s3_client = Rarr:::.create_s3_client(chick))
img_array <- read_image(group = chick, s3_client = Rarr:::.create_s3_client(chick))
```

Read remote data

```{r read s3, eval = FALSE}
chick <- "https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0073A/9798462.zarr"
chick_meta <- read_ome_metadata(group = chick, s3_client = Rarr:::.create_s3_client(chick))
chick_img <- read_image(group = chick)
```

## Write multiscale image

```{r write-multiscale}
# image
img_file <- system.file("images", "sample.png", package="EBImage")
img_array <- readImage(img_file)

# zarr store
store <- tempfile(fileext = ".zarr")

# write
write_image(img_array, 
            group = store, 
            storage_options = list(chunk_dim = c(64,64)))

# read back
img_array <- read_image(group = store)
```

# Session info

```{r sessionInfo, echo=FALSE}
sessionInfo()
```